name = "myblog"
compatibility_date = "2025-12-04"

# Configuraci√≥n para Cloudflare Pages
pages_build_output_dir = "public"

[build]
command = "bash build.sh"
cwd = ""

[build.upload]
format = "directory"
dir = "public"
